# -*- coding: utf-8 -*-
"""nlp-dl-03-answer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IMOJKmjx4V1RRGuNNUWZodNJKcawAFo

# Lab Solution: Building a Batched Dot-Product Attention Module
Here is the completed implementation explaining the tensor permutations required for batched dot-product attention.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class DotProductAttention(nn.Module):
    def __init__(self):
        super(DotProductAttention, self).__init__()

    def forward(self, query, key, value):
        """
        query shape: (batch_size, 1, hidden_dim)
        key shape: (batch_size, seq_len, hidden_dim)
        value shape: (batch_size, seq_len, hidden_dim)
        """
        # 1. Calculate scores using batch matrix multiplication.
        # We use .transpose(1, 2) to swap the seq_len and hidden_dim dimensions.
        # Now key is (batch_size, hidden_dim, seq_len)
        # bmm: (B, 1, H) @ (B, H, S) -> (B, 1, S)
        scores = torch.bmm(query, key.transpose(1, 2))
        # torch.bmm is used for batch matrix multiplication. It multiplies each query vector with all key vectors to get a score for each position in the sequence.

        # 2. Apply softmax across the sequence length dimension (dim=-1 or dim=2)
        attn_weights = F.softmax(scores, dim=-1)

        # 3. Multiply weights by values
        # bmm: (B, 1, S) @ (B, S, H) -> (B, 1, H)
        context = torch.bmm(attn_weights, value)
        # torch.bmm is used again to compute the weighted sum of the value vectors based on the attention weights, resulting in a context vector that summarizes the relevant information from the input sequence.

        return context, attn_weights

# TEST THE CODE
batch_size, seq_len, hidden_dim = 2, 4, 8
torch.manual_seed(42)

q = torch.randn(batch_size, 1, hidden_dim)
k = torch.randn(batch_size, seq_len, hidden_dim)
v = k

attention = DotProductAttention()
context, weights = attention(q, k, v)

print("Context Shape:", context.shape)
print("Weights Shape:", weights.shape)
print("Sum of weights:\n", weights.sum(dim=-1))