# -*- coding: utf-8 -*-
"""nlp-dl-04-answer-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LCrtCDqQT8KL3Wc75Q_USHi4pjF84Vv

# Lab 4: Building the Transformer Encoder (Solution Guide)
**Course:** NATURAL LANGUAGE PROCESSING WITH DEEP LEARNING (2026)  
**Lecturer:** Asst. Prof. Nont Kanungsukkasem, Ph.D.  

This notebook contains complete, mathematically precise implementations for Positional Encoding and Multi-Head Attention matching the structural roadmap guidelines.
"""

import torch
import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)

        # Create a column vector of spatial index tokens [max_len, 1]
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)

        # Calculate geometric frequency step values step-by-step
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        # Broadcast signals evenly into orthogonal vector subspaces matrix channels
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)  # Shape expanded to accommodate batch processing: [1, max_len, d_model]
        self.register_buffer('pe', pe)

    def forward(self, x):
        # slice PE to match sequence length
        x = x + self.pe[:, :x.size(1), :]
        return x

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        assert d_model % num_heads == 0, "d_model must be divisible by num_heads"

        self.num_heads = num_heads
        self.d_model = d_model
        self.d_k = d_model // num_heads

        # Unified parameters matching slide presentation vocabulary layouts
        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)

    def forward(self, x):
        batch_size, seq_len, _ = x.size()  # [B, T, C]

        # Project and restructure spatial tracks: [B, T, C] -> [B, T, heads, d_k] -> [B, heads, T, d_k]
        Q = self.W_q(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)
        K = self.W_k(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)
        V = self.W_v(x).view(batch_size, seq_len, self.num_heads, self.d_k).transpose(1, 2)

        # Core scaled dot-product attention calculation mapping steps
        # Scores matrix size maps to token relationships space: [Batch, heads, seq_len, seq_len]
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)

        # softmax over the last dim -> attention weights
        attn_weights = torch.softmax(scores, dim=-1)

        # compute context vector
        context = torch.matmul(attn_weights, V)  # [B, heads, T, d_k]

        # merge heads: [B,h,T,d_k] -> [B,T,d_model]
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)

        return self.W_o(context)

# ==========================================
# VERIFICATION BLOCK: TEST YOUR CODE HERE
# ==========================================
if __name__ == "__main__":
    print("-> Initializing Test Scenario Environment Simulation...")
    sample_tensor = torch.rand(2, 5, 512)  # [Batch: 2, Seq_Len: 5, d_model: 512]
    print(f"Initial Input Embedded Matrix Shape : {list(sample_tensor.shape)}")

    try:
        # Test 1: Positional Encoding Pass
        pe_layer = PositionalEncoding(d_model=512)
        positioned_tensor = pe_layer(sample_tensor)
        print(f"[PASS] Positional Encoding Output Shape : {list(positioned_tensor.shape)}")

        # Test 2: Multi-Head Attention Pass
        mha_layer = MultiHeadAttention(d_model=512, num_heads=8)
        output_tensor = mha_layer(positioned_tensor)
        print(f"[PASS] Multi-Head Attention Output Shape  : {list(output_tensor.shape)}")

        # Test 3: Shape Invariance Check
        assert sample_tensor.shape == output_tensor.shape, "Dimension transformation error! Shape changed."
        print("\n[SUCCESS] Structural Shape Invariance verified successfully! Ready for submission.")
    except Exception as e:
        print(f"\n[FAIL] Execution error occurred: {str(e)}")
        print("Review matrix operations and transposition dimensions closely.")