# -*- coding: utf-8 -*-
"""NLP-DL-06-lab_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZExApGOKMmV29dD0hTcdM_xXnZpVK-Zr

# Week 6 Lab Solutions: Production Fine-Tuning Pipeline
**Course**: Natural Language Processing with Deep Learning (2026)  
**Assignment**: Custom DeBERTa Classification Head (Rigorous Engineering)

In this assignment, you will implement a fine-tuning pipeline using the state-of-the-art **DeBERTa-v3** architecture. You will discard the high-level HuggingFace abstractions and build a custom PyTorch `nn.Module` head from scratch. You will also employ advanced VRAM optimization techniques including Dynamic Padding, Layer Freezing, Mixed Precision, and Gradient Accumulation.

This is the master solution file.

### Part 1: Production Package Installation & Verification
Acquire, verify, and lock down environment dependencies.
"""

# import os
# os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
# import torch
# try:
#     del model, optimizer, inputs  # Delete large objects
# except NameError:
#     pass
# # torch.cuda.empty_cache()      # If on CUDA
# # or for macOS MPS:
# torch.mps.empty_cache()
# import gc
# gc.collect()

# !pip install -U -q transformers datasets "torch>=2.6.0" evaluate huggingface_hub sentencepiece protobuf tiktoken

import torch
import torch.nn as nn
import numpy as np
import evaluate
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, TrainingArguments, Trainer, DataCollatorWithPadding
print("System Status: Core packages loaded successfully.")

"""### Part 2: Dynamic Hardware Device Detection Layer
Configure device tracking properties to automatically leverage hardware acceleration.
"""

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(f"Target computation engine routed to device: {device.type.upper()}")

"""### Part 3: Targeted Corpus Ingestion (Subsampling)
Pull input distributions and shuffle to extract an approximately balanced sample, to prevent sequential class biases.
"""

# Load full train split, shuffle to mix Positive/Negative, and select 2000 samples
full_corpus = load_dataset("stanfordnlp/imdb", split="train")
subset = full_corpus.shuffle(seed=42).select(range(2000))
tokenized_datasets = subset.train_test_split(test_size=0.2, seed=42)
print("Dataset distributions locked.")

"""### Part 4: Tokenizer Ingestion & Dynamic Padding
Load subword parsing weights for `microsoft/deberta-v3-base`. Rather than wasting VRAM by padding everything to max length, we use `DataCollatorWithPadding` to dynamically pad batches.

**Advanced Edge Case:** *What happens to our VRAM optimization if one sequence in a batch is 512 tokens long, while the other 7 are only 20 tokens?*
The entire batch gets padded to 512! In real-world production, we use **Smart Batching** (sorting sequences by length prior to batching) to mitigate this.
"""

tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-v3-base")

def tokenize_function(examples):
    # Note: We TRUNCATE here, but we DO NOT PAD. Padding will be handled dynamically later.
    return tokenizer(examples["text"], truncation=True, max_length=128)

processed_datasets = tokenized_datasets.map(tokenize_function, batched=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
print("Dynamic padding collator successfully initialized.")

"""### Part 5: Custom nn.Module Wrapper & Layer Freezing
Instead of relying on the `AutoModelForSequenceClassification` black box, you must construct a raw PyTorch class that inherits from `nn.Module`.
You will manually load `AutoModel` (which returns raw hidden states), extract the `[CLS]` token, pass it through a `Dropout` layer (to prevent overfitting), and then through your own `nn.Linear` projection head.

**Layer Freezing**: We put the first 6 layers of the transformer "in ice" so their weights don't move during training (`requires_grad = False`).
**VRAM Math**: The Adam optimizer stores running averages that consume **8 bytes per parameter** in FP32 (4 bytes for momentum + 4 bytes for variance). Freezing also prevents PyTorch from allocating `.grad` tensors, saving an **additional 4 bytes per parameter**. Total savings: **12 bytes per frozen parameter**!

**PyTorch Syntax Reminder**: `outputs.last_hidden_state` has shape `[batch_size, seq_length, hidden_size]`. To grab the first token (the `[CLS]` equivalent) from every sample in the batch, use `[:, 0, :]` — this means *all batches, token index 0, all hidden dimensions*.

**Why `.view(-1)`?** The `.view(-1)` call flattens a tensor into 1D. We use `.view(-1, num_labels)` on logits to ensure shape `[batch_size, 2]` and `.view(-1)` on labels to ensure shape `[batch_size]`, which is what `CrossEntropyLoss` expects.
"""

class CustomDebertaClassifier(nn.Module):
    def __init__(self, num_labels=2):
        super(CustomDebertaClassifier, self).__init__()
        self.num_labels = num_labels
        self.deberta = AutoModel.from_pretrained("microsoft/deberta-v3-base", torch_dtype=torch.float32)
        self.dropout = nn.Dropout(0.1)  # Prevent overfitting on small datasets
        self.classifier = nn.Linear(self.deberta.config.hidden_size, num_labels)
        self.config = self.deberta.config  # Needed by Trainer
        self.config.id2label = {0: "Negative 🔴", 1: "Positive 🟢"}
        self.config.label2id = {"Negative 🔴": 0, "Positive 🟢": 1}

        # Freeze bottom 6 layers (MUST use nested loop — slicing nn.ModuleList returns a plain list!)
        for layer in self.deberta.encoder.layer[:6]:
            for param in layer.parameters():
                param.requires_grad = False

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        outputs = self.deberta(input_ids=input_ids, attention_mask=attention_mask)
        # Extract the [CLS] token: shape [batch_size, seq_len, 768] → [:, 0, :] → [batch_size, 768]
        sequence_output = outputs.last_hidden_state
        cls_token_state = sequence_output[:, 0, :]

        cls_token_state = self.dropout(cls_token_state)
        logits = self.classifier(cls_token_state)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            # .view(-1, 2) flattens logits to [batch, 2]; .view(-1) flattens labels to [batch]
            loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))

        from transformers.modeling_outputs import SequenceClassifierOutput
        return SequenceClassifierOutput(loss=loss, logits=logits, hidden_states=outputs.hidden_states)

model = CustomDebertaClassifier(num_labels=2)
print("Custom DeBERTa model loaded and bottom 6 layers frozen.")

"""### Part 6: Multi-Metric Framework Design
We use `np.argmax(logits, axis=-1)` to pick the highest probability column per row.

**Important Note**: You must initialize `evaluate.load()` *outside* the `compute_metrics` function! If you put it inside, the Trainer will attempt to download the metric scripts from the internet every 50 steps, grinding your training loop to a halt.
"""

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    return {
        **accuracy_metric.compute(predictions=predictions, references=labels),
        **f1_metric.compute(predictions=predictions, references=labels),
        **precision_metric.compute(predictions=predictions, references=labels),
        **recall_metric.compute(predictions=predictions, references=labels),
    }

"""### Part 7: Execution Profiles and Step Evaluation Loops
Configure trainer. To further optimize memory, implement `fp16` mixed precision and **Gradient Accumulation** (which acts like carrying water in small buckets repeatedly instead of trying to carry one impossibly heavy tub all at once).
"""

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=16,  # Simulates batch size 32 (16 buckets of 8)
    fp16=False,                      # Mixed precision for VRAM savings
    dataloader_pin_memory=False,     # Prevents Apple Silicon MPS memory leaks/crashes
    num_train_epochs=1,
    eval_strategy="steps",
    eval_steps=50,
    logging_steps=10,
    metric_for_best_model="f1",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=processed_datasets["train"],
    eval_dataset=processed_datasets["test"],
    compute_metrics=compute_metrics,
    data_collator=data_collator,    # Injects the dynamic padding logic
)

print("--- Starting Optimization Training Phase ---")
trainer.train()
print(trainer.evaluate())

"""### Part 8: Test the model with new sentences on the GPU
Test your optimized weights by manually inputting new out-of-domain text strings.
"""

print("\n--- Instantiating Out-of-Domain Manual Inference Evaluation Suite ---")
model.eval()

unseen_test_phrases = [
    "This movie is an absolute masterpiece. The direction was elegant and the cast was spectacular!",
    "What an abysmal waste of money. The screenplay was messy and the actors delivered stale performances.",
    "The production value was decent, but the pacing felt incredibly slow during the middle chapters."
]

inference_inputs = tokenizer(unseen_test_phrases, padding=True, truncation=True, max_length=128, return_tensors="pt")

# Manually move parameters to the specific routed accelerator hardware target
model.to(device)
inference_inputs = {tensor_key: tensor_val.to(device) for tensor_key, tensor_val in inference_inputs.items()}

with torch.no_grad():
    model_outputs = model(**inference_inputs)
    raw_logits = model_outputs.logits.cpu().numpy()
    calculated_probabilities = torch.softmax(model_outputs.logits, dim=-1).cpu().numpy()

print("\n=== Verification Prediction Breakdown ===")
for index, sequence_text in enumerate(unseen_test_phrases):
    assigned_class_idx = np.argmax(calculated_probabilities[index])
    confidence_score = calculated_probabilities[index][assigned_class_idx]

    assigned_string_output = model.config.id2label[assigned_class_idx]

    print(f"\nSequence Input:    \"{sequence_text}\"")
    print(f"Raw Logit Tensors: {raw_logits[index]}")
    print(f"Assigned Output:   {assigned_string_output}")
    print(f"Confidence Level:  {(confidence_score * 100):.2f}%")

