# -*- coding: utf-8 -*-
"""NLP-DL-07-lab_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JiVFe0Adso_Z7KQR-6VTghFBJ0x8q8jz

# Week 7 Lab: Modern Decoder Architectures (Solutions)
In this lab, you will implement the key components of modern LLMs from scratch.
"""

import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import GPT2LMHeadModel, GPT2Tokenizer

torch.manual_seed(42)

"""## Task 1: RMSNorm Forward
**Learning Objective:** Implement Root Mean Square Normalization.
**Formula:** $y = \frac{x}{\sqrt{\frac{1}{d} \sum_{i=1}^{d} x_i^2 + \epsilon}} \odot \gamma$\n
**Expected Shapes:** Input `(batch, seq, dim)`, Output `(batch, seq, dim)`
**Hints:**
1. Square the input (`x.to(torch.float32).pow(2)`) to avoid FP16 overflow.
2. Calculate the mean over the last dimension (`mean(dim=-1, keepdim=True)`)
3. Use `torch.rsqrt` for $1/\sqrt{\text{variance} + \epsilon}$
4. Cast back to the original dtype (`.to(x.dtype)`) before multiplying by `self.weight`.
"""

class RMSNorm(nn.Module):
    def __init__(self, dim, eps=1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim)) # Shape: (dim,)

    def forward(self, x):
        # x: (batch_size, seq_len, dim)
        # 1. Calculate variance in float32 for numerical stability
        variance = x.to(torch.float32).pow(2).mean(dim=-1, keepdim=True) # Shape: (batch_size, seq_len, 1)
        # 2. Normalize and apply learnable weight
        x_norm = x * torch.rsqrt(variance + self.eps).to(x.dtype) # Shape: (batch_size, seq_len, dim)
        return self.weight * x_norm # Shape: (batch_size, seq_len, dim)

# Test cell
test_x = torch.randn(2, 4, 8)
norm = RMSNorm(8)
out = norm(test_x)
try:
    assert out is not None and out.shape == (2, 4, 8), f"Expected shape (2, 4, 8), got {out.shape if out is not None else 'None (not implemented yet)'}"
    print("✅ Task 1 passed!")
except AssertionError as e:
    print(f"❌ {e}")

"""## Task 2: SwiGLU Forward
**Learning Objective:** Implement SwiGLU activation.
**Formula:** $\text{SwiGLU}(x, W_1, W_2, W_3) = (\text{SiLU}(xW_1) \odot xW_3)W_2$
**Expected Shapes:** Input `(batch, seq, in_dim)`, Output `(batch, seq, in_dim)`
**Parameter Budget:** $W_1: \text{in} \times \text{hidden}$, $W_3: \text{in} \times \text{hidden}$, $W_2: \text{hidden} \times \text{in}$. Total parameters = $3 \times \text{in} \times \text{hidden}$.
**Hints:** Use `F.silu` for the Swish activation.\n
<br>*(Note: we follow LLaMA's w1/w3/w2 naming; the slide uses Shazeer's W1/W2/W3)*
"""

class SwiGLU(nn.Module):
    def __init__(self, in_dim, hidden_dim):
        super().__init__()
        self.w1 = nn.Linear(in_dim, hidden_dim, bias=False)
        self.w3 = nn.Linear(in_dim, hidden_dim, bias=False)
        self.w2 = nn.Linear(hidden_dim, in_dim, bias=False)

    def forward(self, x):
        # x: (batch_size, seq_len, in_dim)
        gate = F.silu(self.w1(x)) # (batch_size, seq_len, hidden_dim)
        val = self.w3(x)          # (batch_size, seq_len, hidden_dim)
        hidden = gate * val       # (batch_size, seq_len, hidden_dim)
        return self.w2(hidden)    # (batch_size, seq_len, in_dim)

# Test cell
test_x = torch.randn(2, 4, 8)
swiglu = SwiGLU(8, 16)
out = swiglu(test_x)
try:
    assert out is not None and out.shape == (2, 4, 8), f"Expected shape (2, 4, 8), got {out.shape if out is not None else 'None (not implemented yet)'}"
    print("✅ Task 2 passed!")
except AssertionError as e:
    print(f"❌ {e}")

"""## Task 3: Apply RoPE
**Learning Objective:** Apply precomputed RoPE frequencies to queries and keys.
**Expected Shapes:** Input `xq, xk: (batch, seq, heads, dim)`, Output `(batch, seq, heads, dim)`
**Hints:**
1. Reshape `xq` and `xk` into complex representations using `torch.view_as_complex`. The last dim becomes `dim // 2`.
2. Multiply by `freqs_cis`.
3. Use `torch.view_as_real` and `flatten(3)` to restore the original shape.
"""

def precompute_freqs_cis(dim: int, end: int, theta: float = 10000.0):
    freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device, dtype=torch.float32)
    freqs = torch.outer(t, freqs)
    return torch.polar(torch.ones_like(freqs), freqs)

def apply_rotary_emb(xq, xk, freqs_cis):
    # xq, xk: (batch, seq, heads, dim)
    # 1. Convert to complex
    xq_ = torch.view_as_complex(xq.float().reshape(*xq.shape[:-1], -1, 2)) # (batch, seq, heads, dim//2)
    xk_ = torch.view_as_complex(xk.float().reshape(*xk.shape[:-1], -1, 2)) # (batch, seq, heads, dim//2)

    # 2. Reshape freqs_cis to broadcast: (1, seq, 1, dim//2)
    freqs_cis = freqs_cis.unsqueeze(0).unsqueeze(2)

    # 3. Multiply and convert back
    xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3) # (batch, seq, heads, dim)
    xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3) # (batch, seq, heads, dim)

    return xq_out.type_as(xq), xk_out.type_as(xk)

# Test cell
dim, seq = 16, 5
freqs = precompute_freqs_cis(dim, seq)
q = torch.randn(2, seq, 4, dim)
k = torch.randn(2, seq, 4, dim)
try:
    result = apply_rotary_emb(q, k, freqs)
    assert result is not None, "Return value is None — have you implemented apply_rotary_emb?"
    q_out, k_out = result
    assert q_out.shape == q.shape and k_out.shape == k.shape
    print("✅ Task 3 passed!")
except (AssertionError, TypeError) as e:
    print(f"❌ {e}")

"""## Task 4: Causal Attention
**Learning Objective:** Implement standard scaled dot-product attention with a causal mask.
**Formula:** $\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d}} + M\right)V$
**Expected Shapes:** $Q, K, V$: `(batch, seq, dim)`, Output `(batch, seq, dim)`
**Hints:**
1. Use `torch.tril(torch.ones(seq, seq))` to create a lower triangular mask.
2. Apply `torch.where` to set 0s to `-inf`.
"""

def causal_attention(q, k, v):
    # q, k, v: (batch, seq, dim)
    bs, seq, dim = q.shape

    # 1. Dot product
    scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(dim) # (batch, seq, seq)

    # 2. Causal mask
    mask = torch.tril(torch.ones(seq, seq)).view(1, seq, seq)
    scores = torch.where(mask == 0, torch.tensor(float('-inf')), scores)

    # 3. Softmax and value multiplication
    attn = F.softmax(scores, dim=-1)
    out = torch.matmul(attn, v) # (batch, seq, dim)
    return out

# Test cell
q = k = v = torch.randn(2, 4, 16)
out = causal_attention(q, k, v)
try:
    assert out is not None and out.shape == (2, 4, 16), f"Expected shape (2, 4, 16), got {out.shape if out is not None else 'None (not implemented yet)'}"
    print("✅ Task 4 passed!")
except AssertionError as e:
    print(f"❌ {e}")

"""## Task 5: Grouped-Query Attention (GQA) `repeat_kv`
**Learning Objective:** Implement the KV repetition step for GQA.
**Expected Shapes:** Input `(batch, seq, n_kv_heads, head_dim)`, Output `(batch, seq, n_kv_heads * n_rep, head_dim)`
**Hints:** Expand a new dimension after `n_kv_heads`, expand to `n_rep`, and then reshape.
"""

def repeat_kv(x, n_rep):
    # x: (batch, seq, n_kv_heads, head_dim)
    bs, slen, n_kv_heads, head_dim = x.shape
    if n_rep == 1:
        return x

    # 1. Add dimension: (batch, seq, n_kv_heads, 1, head_dim)
    # 2. Expand: (batch, seq, n_kv_heads, n_rep, head_dim)
    # 3. Reshape: (batch, seq, n_kv_heads * n_rep, head_dim)
    return x.unsqueeze(3).expand(bs, slen, n_kv_heads, n_rep, head_dim).reshape(bs, slen, -1, head_dim)

# Test cell
kv = torch.randn(2, 5, 2, 8) # 2 KV heads
rep_kv = repeat_kv(kv, 4)   # repeat 4 times -> 8 heads
try:
    assert rep_kv is not None and rep_kv.shape == (2, 5, 8, 8), f"Expected shape (2, 5, 8, 8), got {rep_kv.shape if rep_kv is not None else 'None (not implemented yet)'}"
    print("✅ Task 5 passed!")
except AssertionError as e:
    print(f"❌ {e}")

"""## Task 6: KV Cache Memory Calculation
**Learning Objective:** Calculate KV Cache memory usage.
Calculate the memory (in MB) for: Batch size=4, Sequence length=2048, Head dimension=128, 32 layers, FP16 (2 bytes/param).
Compare MHA (32 heads) and GQA (8 heads).
**Formula:** `2 * batch * seq * n_kv_heads * head_dim * n_layers * bytes_per_param / (1024 * 1024)`
"""

def calc_kv_cache(batch, seq, n_kv_heads, head_dim, n_layers, bytes_per_param=2):
    # Calculate total elements: K and V (hence * 2) across all layers
    elements = 2 * batch * seq * n_kv_heads * head_dim * n_layers
    bytes_total = elements * bytes_per_param
    return bytes_total / (1024 * 1024)

mha_mem = calc_kv_cache(4, 2048, 32, 128, 32)
gqa_mem = calc_kv_cache(4, 2048, 8, 128, 32)
print(f"MHA Memory (32 layers): {mha_mem} MB")
print(f"GQA Memory (32 layers): {gqa_mem} MB")

"""## Task 7 (Bonus): Mini Modern Decoder Block
**Learning Objective:** Combine components into a modern transformer block.
**Structure:** `x = x + Attention(RMSNorm(x))`, then `x = x + SwiGLU(RMSNorm(x))`
"""

class ModernDecoderBlock(nn.Module):
    def __init__(self, dim, hidden_dim):
        super().__init__()
        self.norm1 = RMSNorm(dim)
        # Simplified attention using our causal_attention
        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)

        self.norm2 = RMSNorm(dim)
        self.ffn = SwiGLU(dim, hidden_dim)

    def forward(self, x):
        # 1. Attention block
        h = self.norm1(x)
        q, k, v = self.q_proj(h), self.k_proj(h), self.v_proj(h)
        attn_out = causal_attention(q, k, v)
        x = x + self.out_proj(attn_out)

        # 2. FFN block
        h = self.norm2(x)
        x = x + self.ffn(h)
        return x

# Test cell
block = ModernDecoderBlock(16, 64)
x = torch.randn(2, 10, 16)
out = block(x)
try:
    assert out is not None and out.shape == (2, 10, 16), f"Expected shape (2, 10, 16), got {out.shape if out is not None else 'None (not implemented yet)'}"
    print("✅ Task 7 passed!")
except AssertionError as e:
    print(f"❌ {e}")

"""## Task 8: Manual Generation with KV Cache
**Learning Objective:** Implement a manual autoregressive loop using `past_key_values`.
**Hints:**
1. In the loop, pass `past_key_values` to the model.
2. The model returns `logits` and the updated `past_key_values`.
3. Use the latest logit (index `[:, -1, :]`) to get the next token using `argmax`.
4. Append the next token to your sequence. For the next step, you only need to pass the *new* token to the model, along with the `past_key_values`!
"""

model_id = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_id)
model = GPT2LMHeadModel.from_pretrained(model_id)
model.eval()

prompt = "The capital of France is"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

generated_ids = input_ids.clone()
past_kv = None
next_input = input_ids

print("Starting generation...")
with torch.no_grad():
    for _ in range(5): # Generate 5 tokens
        # Pass input and past_kv
        outputs = model(next_input, past_key_values=past_kv)

        # Get next token from the last logit
        next_token_logits = outputs.logits[:, -1, :]
        next_token = torch.argmax(next_token_logits, dim=-1, keepdim=True)

        # Update past_kv and sequence
        past_kv = outputs.past_key_values
        generated_ids = torch.cat([generated_ids, next_token], dim=-1)

        # Next input is ONLY the newly generated token
        next_input = next_token

print("Generated:", tokenizer.decode(generated_ids[0]))

"""## Task 9: CLM Loss Implementation
**Learning Objective:** Manually calculate the causal language modeling loss by shifting logits and labels.
**Hints:**
1. Logits should predict the *next* token. So `shift_logits` takes all but the last prediction.
2. Labels should be the *actual* next token. So `shift_labels` takes all but the first token.
3. Flatten both before passing to `CrossEntropyLoss`.
"""

loss_fct = nn.CrossEntropyLoss()

# Fake data
vocab_size = 50
seq_len = 10
logits = torch.randn(2, seq_len, vocab_size) # (batch, seq, vocab)
labels = torch.randint(0, vocab_size, (2, seq_len)) # (batch, seq)

# 1. Shift
shift_logits = logits[..., :-1, :].contiguous() # (batch, seq-1, vocab)
shift_labels = labels[..., 1:].contiguous()     # (batch, seq-1)

# 2. Flatten
flat_logits = shift_logits.view(-1, vocab_size) # (batch * (seq-1), vocab)
flat_labels = shift_labels.view(-1)             # (batch * (seq-1))

# 3. Loss
loss = loss_fct(flat_logits, flat_labels)
print("Manual CLM Loss:", loss.item())

"""## Task 10: Activation Patching / Function Vector
**Learning Objective:** Extract an activation vector from a few-shot prompt context and add it to the residual stream of a zero-shot prompt to observe the logit probability spike.
**Hints:**
1. We will use a pre-trained model and hook into its layers, or simply use the `output_hidden_states=True` flag to get hidden states.
2. We extract the hidden state of the last token from a few-shot prompt (e.g., translation or capitalization).
3. For the zero-shot prompt, we manually add this vector to the embeddings before passing it through the rest of the model, or use a hook to add it at a specific layer.
"""

# Task: Capitalization function vector
few_shot = "cat -> CAT\ndog -> DOG\napple -> APPLE"
zero_shot = "bird ->"

# 1. Get hidden states from few-shot prompt
inputs_few = tokenizer(few_shot, return_tensors="pt")
with torch.no_grad():
    outputs_few = model(**inputs_few, output_hidden_states=True)
    # Extract the vector at layer 6, last token
    layer_idx = 6
    func_vector = outputs_few.hidden_states[layer_idx + 1][0, -1, :].clone()  # Shape: (768,)

# 2. Define a hook to patch the vector into the zero-shot forward pass
def patching_hook(module, input, output):
    # In newer transformers, GPT-2 block returns a Tensor directly; in older, a tuple.
    if isinstance(output, tuple):
        hidden = output[0].clone()
        hidden[..., -1, :] += func_vector  # patch last token position
        return (hidden,) + output[1:]
    else:
        # output is a plain Tensor: (seq_len, hidden_size) or (batch, seq_len, hidden_size)
        hidden = output.clone()
        hidden[..., -1, :] += func_vector
        return hidden

# 3. Run zero-shot WITH patching
inputs_zero = tokenizer(zero_shot, return_tensors="pt")

# Register hook at layer 6
handle = model.transformer.h[layer_idx].register_forward_hook(patching_hook)

with torch.no_grad():
    outputs_patched = model(**inputs_zero)

# Remove hook
handle.remove()

# 4. Compare with unpatched
with torch.no_grad():
    outputs_unpatched = model(**inputs_zero)

patched_logits = outputs_patched.logits[0, -1, :]
unpatched_logits = outputs_unpatched.logits[0, -1, :]

print("Unpatched top predictions for 'bird':")
top_unpatched = torch.topk(F.softmax(unpatched_logits, dim=-1), 3)
for i in range(3):
    print(f"- {tokenizer.decode(top_unpatched.indices[i])}: {top_unpatched.values[i].item():.4f}")

print("\nPatched (with capitalization vector) top predictions for 'bird':")
top_patched = torch.topk(F.softmax(patched_logits, dim=-1), 3)
for i in range(3):
    print(f"- {tokenizer.decode(top_patched.indices[i])}: {top_patched.values[i].item():.4f}")

"""**Note on Task 10 Output:**\n
If you observe that the patched model shifts its highest probability to the newline token `\n` instead of the capitalized word (e.g., ` BIRD`), the experiment is still a success! This indicates that the extracted function vector correctly captured the *structural format* of the few-shot task (which expects a newline after the answer). Because GPT-2 is a small model, it recognizes the structural pattern (outputting `\n` next) more confidently than the semantic task of capitalizing the word 'bird'.
"""