# -*- coding: utf-8 -*-
"""nlp-dl-05-solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aUBn_ChkUiIgw3iqKQcibpFuXeuOqbV

# Lab Solution: Decoding Strategies with Hugging Face & Raw PyTorch
This workbook contains the solution setups for checking high-level model execution alongside the custom logit truncation algorithm implementation.
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

model.to(device)
prompt = "In the future, artificial intelligence will"
inputs = tokenizer(prompt, return_tensors='pt').to(device)

"""### Task 1: Greedy Decoding
Solution for generating text using greedy search (`do_sample=False`).
"""

# Task 1: Greedy Search
output_greedy = model.generate(
    inputs.input_ids,
    max_length=50,
    pad_token_id=tokenizer.eos_token_id,
    do_sample=False # set to False to strictly execute argmax maximization
)
print("Greedy Search Output:\n", tokenizer.decode(output_greedy[0], skip_special_tokens=True))

"""### Task 2: Temperature, Top-k & Top-p Sampling Funnel
Solution for experimenting with stochastic decoding strategies across pipeline layers.
"""

# Task 2: High-Level Parametric Sampling Funnel Configurations

out_low_temp = model.generate(
    inputs.input_ids, max_length=50, pad_token_id=tokenizer.eos_token_id,
    do_sample=True, temperature=0.1
)
print("\nTemp 0.1 Output:\n", tokenizer.decode(out_low_temp[0], skip_special_tokens=True))

out_high_temp = model.generate(
    inputs.input_ids, max_length=50, pad_token_id=tokenizer.eos_token_id,
    do_sample=True, temperature=2.0
)
print("\nTemp 2.0 Output:\n", tokenizer.decode(out_high_temp[0], skip_special_tokens=True))

out_top_k = model.generate(
    inputs.input_ids, max_length=50, pad_token_id=tokenizer.eos_token_id,
    do_sample=True, temperature=0.7, top_k=50
)
print("\nTop-k (50) + Temp (0.7) Output:\n", tokenizer.decode(out_top_k[0], skip_special_tokens=True))

out_production_funnel = model.generate(
    inputs.input_ids, max_length=50, pad_token_id=tokenizer.eos_token_id,
    do_sample=True, temperature=0.7, top_k=50, top_p=0.9
)
print("\nProduction Funnel (Temp 0.7 + Top-k 50 + Top-p 0.9) Output:\n", tokenizer.decode(out_production_funnel[0], skip_special_tokens=True))

"""### Task 3: Code-Level Programming Milestone Challenge (Manual Logit Masking) - Solution
The block below implements the complete manual array masking algorithm step-by-step using custom slicing methods.
"""

def top_k_top_p_filtering(logits, top_k=0, top_p=0.0, filter_value=-float('Inf')):
    logits = logits.squeeze(0)

    # 1. Apply Top-K Masking
    if top_k > 0:
        indices_to_remove = logits < torch.topk(logits, top_k)[0][..., -1, None]
        logits[indices_to_remove] = filter_value

    # 2. Apply Top-P (Nucleus) Masking
    if top_p > 0.0:
        sorted_logits, sorted_indices = torch.sort(logits, descending=True)
        sorted_probabilities = torch.softmax(sorted_logits, dim=-1)

        # Formulate cumulative probability arrays natively
        cumulative_probs = torch.cumsum(sorted_probabilities, dim=-1)

        # Shift mask to ensure the threshold token itself is preserved
        sorted_indices_to_remove = cumulative_probs > top_p
        sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
        sorted_indices_to_remove[..., 0] = 0

        # Map indices back into base un-sorted orientation
        indices_to_remove = sorted_indices[sorted_indices_to_remove]
        logits[indices_to_remove] = filter_value

    return logits.unsqueeze(0)

# Execute manual forward computation step loop verification
temperature = 0.7
top_k = 50
top_p = 0.9

with torch.no_grad():
    outputs = model(inputs.input_ids)
    next_token_logits = outputs.logits[:, -1, :] / temperature

    filtered_logits = top_k_top_p_filtering(next_token_logits, top_k=top_k, top_p=top_p)
    probabilities = torch.softmax(filtered_logits, dim=-1)
    next_token = torch.multinomial(probabilities, num_samples=1)

    print("\n--- Verification Manual Autoregressive Code Execution ---")
    print("Manual Next Token Identity ID:", next_token.item())
    print("Manual Next Token Text String:", tokenizer.decode(next_token[0]))