# -*- coding: utf-8 -*-
"""nlp-dl-02-answer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uq4dB5YcmTYLxNOv1aRPwN5ID40Qf48G

# Lab 2 Solution: Char-LSTM
"""

import torch
import torch.nn as nn

if torch.cuda.is_available():
    device = torch.device("cuda")      # NVIDIA GPUs
    print(f"Using CUDA device: {torch.cuda.get_device_name(0)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")       # Apple Silicon GPUs
    print("Using Apple Silicon GPU (MPS)")
else:
    device = torch.device("cpu")       # Fallback
    print("Using CPU")

text = "natural language processing with deep learning is fascinating"
chars = sorted(list(set(text)))
vocab_size = len(chars)
char_to_ix = {ch: i for i, ch in enumerate(chars)}
ix_to_char = {i: ch for i, ch in enumerate(chars)}

data = [char_to_ix[c] for c in text]
seq_len = 10
X, Y = [], []
for i in range(len(data) - seq_len):
    X.append(data[i:i+seq_len])
    Y.append(data[i+1:i+seq_len+1])
X = torch.tensor(X)
Y = torch.tensor(Y)
X = X.to(device)
Y = Y.to(device)

class CharLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x):
        embeds = self.embedding(x)
        lstm_out, _ = self.lstm(embeds)
        logits = self.fc(lstm_out)
        return logits

model = CharLSTM(vocab_size, embed_dim=16, hidden_dim=32).to(device)
criterion = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(150):
    optimizer.zero_grad()
    logits = model(X)
    loss = criterion(logits.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    if (epoch+1) % 50 == 0:
        print(f'Epoch [{epoch+1}/150], Loss: {loss.item():.4f}')

# Auto-regressive generation
model.eval()
with torch.no_grad():
    current_seq = [char_to_ix[c] for c in "natural la"]
    for _ in range(30):
        input_tensor = torch.tensor([current_seq[-seq_len:]])
        input_tensor = input_tensor.to(device)
        logits = model(input_tensor)
        next_char_ix = logits[0, -1, :].argmax().item()
        current_seq.append(next_char_ix)

print("Generated:", ''.join(ix_to_char[ix] for ix in current_seq))